SELECT USER_ID, NICKNAME,
CONCAT(CITY, " ",STREET_ADDRESS1, " ",STREET_ADDRESS2) AS 전체주소,
CASE
    WHEN LENGTH(TLNO) = 10 THEN
    CONCAT(LEFT(TLNO, 3), '-', SUBSTRING(TLNO,4,3),'-', RIGHT(TLNO,4))
    WHEN LENGTH(TLNO) = 11 THEN
    CONCAT(LEFT(TLNO, 3), '-', SUBSTRING(TLNO,4,4),'-', RIGHT(TLNO,4))
    ELSE B.TLNO
    END AS 전화번호1
    
FROM USED_GOODS_BOARD A
LEFT JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
GROUP BY B.USER_ID, B.NICKNAME, B.CITY, B.STREET_ADDRESS1, B.STREET_ADDRESS2, B.TLNO
HAVING COUNT(A.BOARD_ID) >= 3
ORDER BY USER_ID DESC